apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer      # change to NodePort if you’re on bare metal
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
