name: 🧪 Minikube Smoke Test

on:
  pull_request:
    branches:
      - main

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull images into Minikube
        run: |
          docker pull ghcr.io/mikkel077/exam-app/backend:latest
          docker pull ghcr.io/mikkel077/exam-app/frontend:latest
          minikube image load ghcr.io/mikkel077/exam-app/backend:latest
          minikube image load ghcr.io/mikkel077/exam-app/frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/ -R

      - name: Wait for backend rollout
        run: kubectl rollout status deployment/backend --timeout=120s

      - name: Wait for frontend rollout
        run: kubectl rollout status deployment/frontend --timeout=120s

      - name: Smoke test pods
        run: |
          kubectl get pods
