name: Test Backend

on:
  push:
    paths:
      - 'examapp/**'
    branches-ignore:
      - 'docs/**'
  pull_request:
    pull_request:
      - main
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('examapp/pom.xml') }}

      - name: Run backend tests
        run: mvn test -Dtest=SimpleTest

